### ISSUE TITLE
Semicolon is added to most selectors after typing `:`

### ISSUE THREAD

**Issue by indrekpaas** [braver/SublimeSass#3]
When adding a pseudo-class by typing `.class:` the code auto-completes to `.class:;`.

Seems to happen with all selector types other than element and `&` selectors.

Possibly related to #1 .

**Comment by indrekpaas** [comment]
Cheers! Unrelatedly – do you have a list of known bugs you could publish? It would keep people doubling up on the issues you're already aware of.

**Comment by braver** [comment]
Actually this one was off my radar, but usually I fix whatever I find right away or log it here in GitHub.

**Comment by braver** [comment]
@indrekpaas I pushed a bunch of work on master. I basically had to change the approach to matching selectors, and then put everything back together (at the same time improving parity with the default CSS package). I haven't spend a lot of time writing stylesheets with it yet, but it passes all the tests and it looks good as far as I can tell. If you want, you can try it out, see if it fixes this issue for you and works ok otherwise?

**Comment by indrekpaas** [comment]
@braver thanks for the updates, the results are amazing!

**Comment by braver** [comment]
Thanks! One or two small tweaks I need to make and then I'll release the update.

**Comment by tigrr** [comment]
I am still having this issue.
