### ISSUE TITLE
String arguments in a function named color()

### ISSUE THREAD

**Issue by sandrojohanides** [braver/SublimeSass#40]
Doesn’t seem to happen with other name than `color()`.

![screen shot 2018-11-26 at 10 38 36](https://user-images.githubusercontent.com/8327913/49012505-e0d21000-f179-11e8-84b1-086306b02d71.png)
```scss
mark {
	box-decoration-break: clone;
	background-color: color(mark, unthemed);
	border-radius: border(normal);
	color: inherit;
}
```
![screen shot 2018-11-26 at 11 01 58](https://user-images.githubusercontent.com/8327913/49012506-e0d21000-f179-11e8-99ae-02bc346341a7.png)
```scss
@mixin faded-border(
	$side: top,
	$oneway: null,
	$color: color(light-grey),
	$border-width: 1,
	$gradient-length: 10%,
	$oneway-start: 0%
) {
```

**Comment by braver** [comment]
`color()` is actually a built in CSS function and takes a specific set of arguments. It does highlight that I need to account for more types of values, variables and functions as arguments for built-in functions.

**Comment by sandrojohanides** [comment]
Oh I see, https://drafts.csswg.org/css-color/#color-function.
- I'm certainly wrong then and should change the function name, but...
- it seems Sass allows for overwriting of CSS *and* Sass functions, so I'm not sure what to do here.

**Comment by braver** [comment]
>it seems Sass allows for overwriting of CSS and Sass functions, so I'm not sure what to do here.

If that’s true, and it probably is, I should allow the same arguments for all functions, built in or not.

**Comment by braver** [comment]
Well, the way I see it, the syntax should primarily try to help you catch typos, end sequences correctly, and in general make the code easier to read. It has an auxiliary function of supplying autocomplete suggestions, and more specific context information makes the suggestions better. But it's not a parser or a linter, or a compiler. So, a syntax only goes so far when it comes to finding syntax errors, or incorrect use of the language. The syntax can't tell if you're overloading a built-in function and cannot know if the compiler will allow you to do so. It might not do so in one version of the compiler, but that capability might be expanded in another version, and Sass/SCSS has several implementations that might be different here too. So, as long as it syntactically looks like SCSS, it's good enough for me.

I can also get rid of a lot of lines of code here by removing the specific built-in functions. So I really like the idea of not being specific with the highlighting here and allow all types of arguments for all functions.

**Comment by sandrojohanides** [comment]
For me, personally, consistency and lack of highlighting errors are the most important points, so I’m in line with this, but can’t speak for others.

**Comment by sandrojohanides** [comment]
This caused some kind of regression in functions with keywords and hyphens (but not when in strings). Didn’t do more testing, sorry!

![screen shot 2018-11-29 at 18 50 23](https://user-images.githubusercontent.com/8327913/49241281-aaa9c000-f407-11e8-98e7-85d960396e87.png)
```scss
.test {
	content: fn(height-width);
	content: fn(width-height);
	content: fn(dark-grey);
	content: fn(grey-grey);
	content: fn(dark-dark);
}
```

**Comment by braver** [comment]
Right, that's a new issue that surfaced by these changes. Unquoted strings are a ****...

**Comment by braver** [comment]
A custom function can take any expression as an argument. And any argument can be used in any way. So, the string `grey` can be passed to a function to mean the grey standard css color, or as a string to be used to compose a selector. Essentially, a string argument that looks like a built-in value, shouldn't be highlighted as a built-in value because it actually isn't. 

I want to keep highlighting built-in values for built-in functions. This cannot co-exist with a big catch-all like "unquoted string". So I will restore the specific built-in functions from the CSS package. This means you don't get 100% consistent highlighting when you override a built-in function, but I think that's a better trade off because overriding built-in functions isn't really a recommended practice.

**Comment by sandrojohanides** [comment]
The way I see it, `grey` could be highlighted as a color (as a compromise), but `dark-grey` shouldn’t (if you can identify the difference). Maybe it would discourage from using 'keywords' as keys, values or agruments.
And yes, overriding built-in functions shoudn’t be encouraged either, but allowed.
I know this is not the responsibility of the syntax, but I see it as a healthy compromise. I might even use qoutes around my custom strings from now on.

**Comment by braver** [comment]
> I might even use qoutes around my custom strings from now on.

Well that helps too, `dark-grey` doesn't actually mean anything and if you quote it that helps future readers of your code to understand that it's a string. 

> The way I see it, grey could be highlighted as a color (as a compromise), but dark-grey shouldn’t (if you can identify the difference)

Well that's just really tricky, because you can use strings, operators and values together, and sometimes you don't need whitespace between them, and it becomes pretty hard to set it up so it matches all those different things correctly. That said, I may return to this later, but I've got more valuable things I want to tackle first.

**Comment by sandrojohanides** [comment]
Riight, I understand now, the `-` operator would be a bitch indeed. Guess I should use `_` in strings instead of using a math operator.

**Comment by braver** [comment]
I'm going to close this, I need to see more cases to work on an improvement if one is needed at all.

**Comment by sandrojohanides** [comment]
This seems to work pretty well for me right now 👍
