### ISSUE TITLE
Pseudo selectors behave differently

### ISSUE THREAD

**Issue by sandrojohanides** [braver/SublimeSass#44]
Are functional pseudo selectors supposed to have a different color? `::slotted()` is white. Also, pseudo class content of `not:()` shouldn’t be blue.

Sources:
- https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements
- https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes

```scss
.test:not(:first-child) {}
.test:not(.test) {}
.test:dir(rtl) {}
.test:nth-child(n + 1) {}
.test:first-child {}
.test::slotted(span) {}
.test::after {}
```
![screen shot 2018-11-27 at 12 11 12](https://user-images.githubusercontent.com/8327913/49078162-92864500-f23d-11e8-8430-8b461c46706d.png)

**Comment by braver** [comment]
It depends on your color scheme what happens exactly, but `:not()` is also scoped as a function call, whereas `:first-child` is not. The arguments are part of the function call, so that's probably also why `:first-child` is blue when passed to `:not()`. We match the CSS syntax here, so I expect that to look the same in a CSS file with your color scheme. Right now at least no cause to expect there to be something wrong, so I'm closing it.

**Comment by sandrojohanides** [comment]
The scheme I’m using doesn’t differentiate between a regular and a functional pseudo class (in `CSS3`), so seeing a difference was new for me I guess.
 
![screen shot 2018-11-27 at 20 57 38](https://user-images.githubusercontent.com/8327913/49107878-1dd7f880-f287-11e8-8004-27f1a8e174c3.png)
