### ISSUE TITLE
[ST4] Update CSS/SASS completions and behaviors

### ISSUE THREAD

**Issue by andremacola** [braver/SublimeSass#66]
![scss](https://user-images.githubusercontent.com/3408809/90666876-66d29c00-e224-11ea-82e9-aacbb68b8fcc.png)

This is an example on SASS file. Without left icons and a _"property"_ commentary on right.

![css](https://user-images.githubusercontent.com/3408809/90666881-6934f600-e224-11ea-8c25-d2dba7b9a92f.png)

This is how ST4 shows the completions now, with icons and no redundant _"property"_ word on right side.

I see that you modified the behavior and added some extra properties to: https://github.com/braver/SublimeSass/blob/master/sass_completions.py

We need to keep the modifications or adopt the sublime ones with sass/scss scope?https://github.com/sublimehq/Packages/blob/master/CSS/css_completions.py

**Comment by braver** [comment]
I already updated LESS with the new features. Sass takes a bit more effort mostly because of the weird optional `:property value` syntax. In any case I should be able to finish before ST4 is out. And I won’t tag a release before that happens because I want to stay in sync with the core CSS package people are using, and don’t want to stumble into any ST3-4 incompatibilities. So, if you wan to start using this, manually install master of this repo instead of the version in package control, at least until ST4 is out.

**Comment by braver** [comment]
With 6b5bd525abf010534ed31335e2f560309d195d8e this should be fixed. As I said, I won't be releasing this until ST4 is released publicly. So if you're using the ST4 beta, check out master of this repo and let me know if it works as you'd expect.
