### ISSUE TITLE
Mixed ST4/ST3 releases

### ISSUE THREAD

**Issue by rchl** [braver/SublimeSass#76]
It looks like the ST4 release was made from the ST3 branch.

Or at least in ST4 there is no option to disable completions in `sass_completions.py`.

**Comment by braver** [comment]
Currently all releases are rolled back to an ST3 compatible version. I’m still waiting for a review in package control so that I can split the releases and bring the new features back for ST4. If you want those things right now, you can manually install master of this repo, instead of going via package control.

**Comment by rchl** [comment]
Can we do this now? :)

**Comment by braver** [comment]
I believe this is already a done deal. Or did the feature you were waiting get lost in the shuffle?

**Comment by braver** [comment]
Oh, or maybe I’m wrong ... I’ll have a look

**Comment by braver** [comment]
🤔 totally forgot to actually tag a new release. Done now! Thanks!
