### ISSUE TITLE
Beta 3.0: Coloration issues

### ISSUE THREAD

**Issue by artik** [braver/SublimeSass#90]
I'm facing a coloration issue since beta 3.0 ( `/2` and `- 5px` are not colored anymore in this example:

![screenshot03](https://user-images.githubusercontent.com/1015856/150222349-9fac723e-d162-44d5-a11f-4a289735267b.png)

Also all Mozilla prefix:

![screenshot05](https://user-images.githubusercontent.com/1015856/150222615-b43f9714-6b6d-4eab-92d8-73697a712d1d.png)

**Comment by braver** [comment]
I don't think I cover vendor prefixes in at all in any "at rules", neither does the default CSS package (which implementation I follow here). `@document` is in fact [deprecated](https://developer.mozilla.org/en-US/docs/Web/CSS/@document). 

The interpolation in calc functions should be fixed in de the upcoming beta update though.
